### ISSUE TITLE
Anyone able to connect to CloudKey with 6.0.43

### ISSUE THREAD

**Issue by MEntOMANdo** [nickovs/unificontrol#18]
Version 6 has similar changes as the UDM Pro, where the admin is now on port 443, and some of the endpoints are tweaked. I gave this only 1 minute, and it wasn't able to connect. I figure I would ask before spending time troubleshooting it. Does this work with 6.0 backends?

**Comment by nickovs** [comment]
I believe that the v6 code on the CloudKey is pretty much the same as the v6 code on the UDM. In fact the UDM that I bought had v5 software on it when it arrived which was identical to that on my CloudKey and I have to upgrade it to make it now work! As such I expect that the new UDM support should help. There's a long thread about this over in Issue #12 and if you want to try out the branch with embryonic UDM support the [this comment](https://github.com/nickovs/unificontrol/issues/12#issuecomment-774787950) discusses how to install it. You will need to include `server_type=UnifiServerType.UDM` on the arguments to the client constructor to enable this support. It would be great if you could give this a try and let me know how you get on, specifically around which functions work for you want which ones do not.

**Comment by MEntOMANdo** [comment]
I'm in! Great stuff!

**Comment by nickovs** [comment]
Thanks @MEntOMANdo It seems that the new controller has totally re-worked the way that stats are reported. It looks like I am going to have to investigate and that and reverse-engineer a whole new API there. If you have the opportunity to post a list of the specific stats calls that fail for you it would be helpful.
