### ISSUE TITLE
SSL error when trying to use any function except the initial connection

### ISSUE THREAD

**Issue by raakatz** [nickovs/unificontrol#24]
Hi there.

If I run only:
```
import unificontrol
import ssl

cert = ssl.get_server_certificate(('hostname', 8443))
controller = unificontrol.UnifiClient(host='hostname', username='support', password='passoword', cert=cert, port=8443)
```
Then it runs and exits with no errors.

But as soon as I write a new line, for example:

`controller.list_sites()`

I get this error:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='hostname', port=8443): Max retries exceeded with url: /api/self/sites (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))
`

It does this with any function I enter

***I didn't write the actual hostname, username, and password in this post, but in the code they are 100% correct

**Comment by raakatz** [comment]
Solved, trick was to have ssl imported and also "cert=None" as an argument in the controller

**Comment by menvol3** [comment]
Hi @raakatz ,

Could you please explain what you did to solve it ?

I’m receiving 
`Max retries exceeded with url: /api/s/default/stat/guest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125)')))`
